{% set name = "ttp" %}
{% set version = "0.9.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ttp-{{ version }}.tar.gz
  sha256: 234414f4d3039d2d1cde09993f89f8db1b34d447f76c6a402555cefac2e59c4e

build:
  entry_points:
    - ttp = ttp.ttp:cli_tool
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.7,<4.0

test:
  imports:
    - ttp
  commands:
    - pip check
    - ttp --help
  requires:
    - pip

about:
  home: https://github.com/dmulyalin/ttp
  summary: Template Text Parser
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cousinbr
